version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: vehiclerental_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vehiclerental
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: VehicleRentalSystem.WebApi/Dockerfile
    depends_on:
      - db
    environment:
      # Same key you use in appsettings.json → "ConnectionStrings:Default"
      ConnectionStrings__Default: "Host=db;Port=5432;Database=vehiclerental;Username=postgres;Password=postgres"
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "5000:8080"

  frontend:
    build:
      context: .
      dockerfile: VehicleRentalSystem.Frontend/Dockerfile
    depends_on:
      - backend
    environment:
      # Adjust if you front your API with a reverse-proxy
      NEXT_PUBLIC_API_BASE_URL: "http://localhost:5000"
    ports:
      - "3000:8080"

volumes:
  postgres-data:
